
title: "Michael Singletary"
tagline: ""
description: "Follow <a href=\"https://micro.blog/singletary\">@singletary on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/singletary\">@singletary on Micro.blog</a>."
baseurl: ""
url: "https://singletary.me"
markdown: "kramdown"
username: "singletary"
microblog_user: "singletary"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Michael Singletary"
name: "Michael Singletary"
gravatar_hash: "3d72bbdbe5f57de805186e0177e8520b"
avatar: "https://micro.blog/singletary/avatar.jpg"
full_name: "Michael Singletary"
bio: ""
twitter_username: "singletary"
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "960"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Michael Singletary"